version: '3'
services:
  futong-yw-k8s:
    image: IMAGE_NAME_FLAG:IMAGE_TAG_FLAG
    ports:
      - 10003:10003
    volumes:
      - /var/log/ftcloud/yw/futong-yw-k8s/logs:/ftcloud/yw/futong-yw-k8s/logs:rw,Z
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      # Flag to load setting info from environment variables
      FLAG_SETTING_FROM_ENV: "exist"

      ####################### Project ########################
      APP_NAME: "ftk8s"
      # Supported parameters: debug,release,test
      APP_RUN_MODE: "debug"
      HTTP_IP: "0.0.0.0"
      HTTP_PORT: "10003"
      # Select the user service, supported parameters: self, cmp
      TYPE_USER_SERVICE: "self"
      # JWT
      TOKEN_EXP_TIME: 86400
      RSA_PRIVATE_KEY: "base/rsakey/rsa-private.pem"
      RSA_PUBLIC_KEY: "base/rsakey/rsa-public.pem"
      # Initialize the administrator
      INIT_TENANT_ID: "admin"
      INIT_TENANT_NAME: "主账号"
      INIT_PASSWORD: "admin_123"
      INIT_EMAIL: ""

      ######################### Log ##########################
      # Supported parameters: debug,info,warn,error,dpanic,panic,fatal
      LOG_LEVEL: "debug"
      LOG_FILE: "logs/ftk8s.log"

      ######################## MySQL #########################
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "FT@k8s2020"
      MYSQL_HOST: "172.16.53.103"
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "ftk8s"
      # Timeout for establishing connections, aka dial timeout.
      # The value must be a decimal number with a unit suffix ("ms", "s", "m", "h"),
      # such as "30s", "0.5m" or "1m30s".
      MYSQL_TIMEOUT: "1m30s"
      MYSQL_MAX_IDLE_CONNS: 100
      MYSQL_MAX_OPEN_CONNS: 1000

